vich_uploader:
    db_driver: orm

    mappings:
        matricula_apoderado:
            uri_prefix:         /uploads/matricula/apoderado
            upload_destination: '%kernel.project_dir%/public/uploads/matricula/apoderado'
            namer:              Vich\UploaderBundle\Naming\SmartUniqueNamer
        matricula_estudiante:
            uri_prefix:         /uploads/matricula/estudiante
            upload_destination: '%kernel.project_dir%/public/uploads/matricula/estudiante'
            namer:              Vich\UploaderBundle\Naming\SmartUniqueNamer
        libro_imagen:
            uri_prefix:         /uploads/imagenes/libros
            upload_destination: '%kernel.project_dir%/public/uploads/imagenes/libros'
            namer:              Vich\UploaderBundle\Naming\SmartUniqueNamer
        item_imagen:
            uri_prefix:         /uploads/imagenes/items
            upload_destination: '%kernel.project_dir%/public/uploads/imagenes/items'
            namer:              Vich\UploaderBundle\Naming\SmartUniqueNamer
        persona_imagen:
            uri_prefix:         /uploads/persona/imagen
            upload_destination: '%kernel.project_dir%/public/uploads/persona/imagen'
            namer:              Vich\UploaderBundle\Naming\SmartUniqueNamer            